# Generated by Django 4.1.3 on 2022-11-08 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rainguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rainguage_code", models.SmallIntegerField(verbose_name="강우량계 코드")),
                (
                    "rainguage_name",
                    models.CharField(max_length=8, verbose_name="강우량계명"),
                ),
                ("gu_code", models.SmallIntegerField(verbose_name="구청 코드")),
                ("gu_name", models.CharField(max_length=8, verbose_name="구청명")),
            ],
        ),
        migrations.CreateModel(
            name="Sewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idn", models.CharField(max_length=8, verbose_name="고유번호")),
                ("gubn", models.CharField(max_length=4, verbose_name="구분코드")),
                ("gubn_nam", models.CharField(max_length=4, verbose_name="구분명")),
                ("remark", models.CharField(max_length=255, verbose_name="위치정보")),
            ],
        ),
        migrations.CreateModel(
            name="Sewage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mea_ymd", models.DateTimeField(verbose_name="측정일자")),
                (
                    "mea_wal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="측정수위"
                    ),
                ),
                ("sig_sta", models.CharField(max_length=8, verbose_name="통신상태")),
                (
                    "sewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.sewer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rainfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rainfall10", models.FloatField(verbose_name="10분우량")),
                ("recieve_time", models.DateTimeField(verbose_name="자료수집 시각")),
                (
                    "rainguage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.rainguage",
                        verbose_name="강우량계",
                    ),
                ),
            ],
        ),
    ]
