# Generated by Django 4.1.3 on 2022-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_gu_alter_rainguage_gu_code_alter_rainguage_gu_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gu",
            name="gubn",
            field=models.CharField(max_length=4, null=True, verbose_name="구분코드"),
        ),
    ]
