# Generated by Django 4.1.2 on 2022-11-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_remove_rainguage_gu_code_remove_rainguage_gu_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gu",
            name="code",
            field=models.SmallIntegerField(
                null=True, unique=True, verbose_name="구청 코드"
            ),
        ),
        migrations.AlterField(
            model_name="gu",
            name="gubn",
            field=models.CharField(
                max_length=2, null=True, unique=True, verbose_name="구분코드"
            ),
        ),
        migrations.AlterField(
            model_name="gu",
            name="name",
            field=models.CharField(max_length=8, unique=True, verbose_name="구청명"),
        ),
    ]
